//! USDC-on-Stellar config + memo generation.
//!
//! Single-platform-wallet model: every USDC payment goes to one
//! receiving address configured via env. Per-publisher wallets are a
//! much harder custody story and explicitly out of scope.
//!
//! Memos are short (Stellar MEMO_TEXT is 28 bytes max), unique, and
//! must survive being copy-pasted by humans — we use base32 (no
//! ambiguous 0/O/1/I) of randomly generated bytes, prefixed with
//! `mp-` so on-chain explorers make it obvious what the memo is.

use rand::Rng;

/// Length of the random portion (24 chars after the `mp-` prefix
/// brings the total to 27, under the 28-byte limit).
const MEMO_RANDOM_LEN: usize = 24;
const ALPHABET: &[u8] = b"ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; // no 0/O/1/I

#[derive(Debug, thiserror::Error)]
pub enum UsdcError {
    #[error("MARKETPLACE_USDC_RECEIVING_ADDRESS is not set")]
    ReceivingAddressMissing,
    #[error("MARKETPLACE_USDC_ASSET_ISSUER is not set")]
    AssetIssuerMissing,
    #[error("MARKETPLACE_USDC_NETWORK must be 'testnet' or 'public' (got {0:?})")]
    BadNetwork(String),
    #[error("receiving address is not a valid Stellar ed25519 public key")]
    BadReceivingAddress,
}

pub struct UsdcConfig {
    pub receiving_address: String,
    pub asset_issuer: String,
    pub network: String,
}

impl UsdcConfig {
    pub fn from_env() -> Result<Self, UsdcError> {
        let receiving_address = std::env::var("MARKETPLACE_USDC_RECEIVING_ADDRESS")
            .map_err(|_| UsdcError::ReceivingAddressMissing)?;
        if !looks_like_stellar_address(&receiving_address) {
            return Err(UsdcError::BadReceivingAddress);
        }
        let asset_issuer = std::env::var("MARKETPLACE_USDC_ASSET_ISSUER")
            .map_err(|_| UsdcError::AssetIssuerMissing)?;
        let network =
            std::env::var("MARKETPLACE_USDC_NETWORK").unwrap_or_else(|_| "testnet".to_string());
        if network != "testnet" && network != "public" {
            return Err(UsdcError::BadNetwork(network));
        }
        Ok(Self {
            receiving_address,
            asset_issuer,
            network,
        })
    }
}

/// Soft check — Stellar account ids start with 'G' and are 56 chars
/// (StrKey-encoded ed25519 public key). We don't decode the StrKey
/// itself here; the indexer (and ultimately Stellar Core) will reject
/// payments sent to a malformed address.
fn looks_like_stellar_address(s: &str) -> bool {
    s.len() == 56 && s.starts_with('G') && s.chars().all(|c| c.is_ascii_alphanumeric())
}

/// Generate a fresh memo. Collisions are vanishingly unlikely (≈
/// 32^24 ≈ 2^120) but the DB has a UNIQUE constraint as belt-and-
/// braces, and the caller retries on conflict.
pub fn generate_memo() -> String {
    let mut rng = rand::thread_rng();
    let body: String = (0..MEMO_RANDOM_LEN)
        .map(|_| {
            let idx = rng.gen_range(0..ALPHABET.len());
            ALPHABET[idx] as char
        })
        .collect();
    format!("mp-{body}")
}

/// Convert a USD cents amount to the integer stroop representation
/// used by Stellar (USDC has 7 decimals: 1 USDC = 10_000_000 stroops).
/// cents → stroops:  cents * 100_000 (because 100 cents = 1 USDC =
/// 10_000_000 stroops, so 1 cent = 100_000 stroops).
pub fn cents_to_usdc_stroops(cents: i64) -> i64 {
    cents.saturating_mul(100_000)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn memo_format_and_length() {
        let m = generate_memo();
        assert!(m.starts_with("mp-"));
        assert_eq!(m.len(), 3 + MEMO_RANDOM_LEN);
        assert!(m.len() <= 28, "stellar memo_text is 28 bytes max");
        let body = &m[3..];
        assert!(body.chars().all(|c| ALPHABET.contains(&(c as u8))));
    }

    #[test]
    fn memos_do_not_collide_within_a_batch() {
        use std::collections::HashSet;
        let memos: HashSet<_> = (0..1000).map(|_| generate_memo()).collect();
        assert_eq!(memos.len(), 1000);
    }

    #[test]
    fn cents_to_stroops_conversion() {
        assert_eq!(cents_to_usdc_stroops(100), 10_000_000); // $1.00 = 1 USDC
        assert_eq!(cents_to_usdc_stroops(1), 100_000); // $0.01
        assert_eq!(cents_to_usdc_stroops(2999), 299_900_000); // $29.99
    }

    #[test]
    fn stellar_address_shape_check() {
        assert!(looks_like_stellar_address(
            "GA5XIQA5C7LTPNM5UWKKVZZIVMUCZL4PQT2W7L2WW3WIQYBBG2QV5XJM"
        ));
        assert!(!looks_like_stellar_address("not-an-address"));
        assert!(!looks_like_stellar_address(
            "MA5XIQA5C7LTPNM5UWKKVZZIVMUCZL4PQT2W7L2WW3WIQYBBG2QV5XJM" // starts with M, not G
        ));
    }
}
